# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/cliqr/usage/templates/**/*'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'lib/cliqr/util.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_util.rb'
    - 'lib/cliqr/config/dsl.rb'
    - 'lib/cliqr/util.rb'

Metrics/AbcSize:
  Max: 16.16
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_util.rb'
    - 'lib/cliqr/util.rb'


Metrics/ClassLength:
  CountComments: false
  Max: 100
  Exclude:
    - 'lib/cliqr/config/action.rb'
    - 'lib/cliqr/util.rb'

Metrics/ParameterLists:
  Max: 6
