# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tasks/**/*'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Exclude:
    - 'spec/**/*_spec.rb'
