# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'templates/**/*'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*_spec.rb'
