# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'templates/**/*'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 15
  Exclude:
    - 'spec/**/*_spec.rb'



Metrics/ClassLength:
  CountComments: false
  Max: 110
