language: ruby
bundler_args: --without guard
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
os:
  - linux
  - osx
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
    - rvm: rbx-2
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: rbx-2
    - os: osx
  fast_finish: true
branches:
  only: master
notifications:
  email: false
env:
  global:
    - secure: fas+p17YULj0EWfJEmcVBRimncqaAubPJeriROmPBIZmwSyGr3ldjSj5f+n9NNobD6BZ3kIredBDcBqlkCGKYVsvM/ULVxkjxLGa9VA28m1wgOgtGlKRD6C7YPP5+Hw74K7G5XF4bspSG6VOfLOiPPtfbCMXymmjKdGzbhKJ594=
